import { test, expect } from '@playwright/test';

test('calculator accepts keyboard and numpad, operators, Enter, Escape and Backspace', async ({ page }) => {
  await page.goto('/#scientific');
  await page.locator('#tool-title').click();
  await page.keyboard.type('12+3');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-result')).toHaveText('15');
  await page.keyboard.type('*2');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-result')).toHaveText('30');
  await page.keyboard.press('Escape');
  await page.keyboard.press('Numpad8');
  await page.keyboard.press('NumpadDivide');
  await page.keyboard.press('Numpad2');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-result')).toHaveText('4');
  await page.keyboard.press('Escape');
  await page.keyboard.type('123');
  await page.keyboard.press('Backspace');
  await expect(page.locator('#calc-expression')).toHaveValue('12');
  await page.keyboard.press('Enter');
  await page.keyboard.type('7');
  await expect(page.locator('#calc-expression')).toHaveValue('7');
  await page.locator('#tool-search').fill('공학');
  await expect(page.locator('#calc-expression')).toHaveValue('7');
  await page.goto('/#counter');
  await page.locator('#input').fill('123');
  await page.keyboard.press('Enter');
  await expect(page.locator('#input')).toHaveValue('123\n');
});

test('scientific buttons, angle mode, history, answer, invalid inputs and result copy', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('/#scientific');
  await page.locator('[data-value="sin("]').click();
  await page.keyboard.type('30)');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-result')).toHaveText('0.5');
  await page.locator('#calc-copy').click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('0.5');
  await page.locator('#calc-expression').fill('ans*4');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-result')).toHaveText('2');
  await page.goto('/#counter');
  await page.goto('/#scientific');
  await expect(page.locator('#calc-result')).toHaveText('2');
  await page.locator('.history-item').first().click();
  await expect(page.locator('#calc-result')).toHaveText('2');
  await page.locator('#calc-angle').selectOption('RAD');
  await page.locator('#calc-expression').fill('sin(pi/2)');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-result')).toHaveText('1');
  await page.locator('#calc-expression').fill('1/0');
  await page.keyboard.press('Enter');
  await expect(page.locator('#calc-error')).toContainText('0으로 나누기');
  await expect(page.locator('#calc-copy')).toBeDisabled();
  await page.locator('#basic-mode').click();
  await expect(page.locator('#science-keys')).toBeHidden();
});

test('graphs redraw, zoom, show errors and download PNG on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#graph');
  await expect(page.locator('#graph-canvas')).toHaveAttribute('aria-label', /sin\(x\)/);
  await page.locator('[data-expression="x^2"]').click();
  await expect(page.locator('#graph-canvas')).toHaveAttribute('aria-label', /x\^2/);
  await page.locator('#graph-zoom-in').click();
  await expect(page.locator('#x-min')).toHaveValue('-2.5');
  await page.locator('#graph-reset').click();
  await expect(page.locator('#x-min')).toHaveValue('-10');
  const download = page.waitForEvent('download');
  await page.locator('#graph-download').click();
  expect((await download).suggestedFilename()).toBe('simple-utils-graph.png');
  await page.locator('#graph-expression').fill('window.alert(1)');
  await expect(page.locator('#graph-error')).not.toBeEmpty();
  await expect(page.locator('#graph-download')).toBeDisabled();
  await page.locator('#graph-expression').fill('x');
  await page.locator('#x-min').fill('20');
  await expect(page.locator('#graph-error')).toContainText('최솟값');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.goto('/#scientific');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test('lunar converter supports direction switching, leap month and invalid dates', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#lunar');
  await page.locator('#lunar-year').fill('2017');
  await page.locator('#lunar-month').fill('6');
  await page.locator('#lunar-day').fill('24');
  await expect(page.locator('#lunar-result')).toHaveText('2017년 5월 1일');
  await expect(page.locator('#lunar-leap-result')).toHaveText('음력 윤달');
  await page.locator('#lunar-to-solar').click();
  await expect(page.locator('#lunar-leap')).toBeChecked();
  await expect(page.locator('#lunar-result')).toHaveText('2017년 6월 24일');
  await page.locator('#lunar-year').fill('2026');
  await page.locator('#lunar-month').fill('1');
  await expect(page.locator('#lunar-copy')).toBeDisabled();
  await page.locator('#lunar-leap').uncheck();
  await expect(page.locator('#lunar-result')).toHaveText('2026년 2월 17일');
  await page.locator('#lunar-year').fill('2051');
  await expect(page.locator('#lunar-result')).toHaveText('—');
  await expect(page.locator('#lunar-copy')).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});
